name: PublishPackage
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Remove everything except assets
      run: |
        rm -rf Images
        rm LICENSE
        rm -rf Packages
        rm -rf ProjectSettings
        rm README.md
    - name: Copy package folder out
      run: |
        mv Assets/Package ../
    - name: Remove assets
      run: rm -rf Assets
    - name: Push to package branch
      env:
        PUSH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.email "marek.magdziak@hotmail.cz"
        git config --global user.name "Marek Magdziak"
        git checkout package
        cp -r ../Package/* .
        git add -A
        git commit -m "Create package"

        git remote set-url origin https://$PUSH_TOKEN:x-oauth-basic@github.com/mkmarek/unity-component-ui.git

        git push --force
